apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    tier: nginx
spec:  
  type: NodePort 
  #type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
    tier: nginx
